About block
Nostradamusx06/Fitness pull request #2
Opened 2024-03-16 09:53 UTC by Nostradamusx06

2024-03-16 17:55 UTC, cherninely requested changes

2024-03-16 17:55 UTC, cherninely commented on source/img/sprite/sprite.svg
Точно картинка нормальная?

2024-03-16 17:55 UTC, cherninely commented on source/index.html
> +    crossorigin="anonymous">
Почему новая строка?

2024-03-16 17:55 UTC, cherninely commented on source/index.html
> +            <svg class="video__button-img" width="100" height="100" viewBox="0 0 100 100" fill="none"
Почему это не отдельным файлом?

2024-03-16 17:55 UTC, cherninely commented on source/js/main.js
>  // import Swiper from "swiper";
Что за лишний код?

2024-03-16 17:55 UTC, cherninely commented on source/js/video.js
> +function findVideos() {
лучше так

```
const findVideo = () => {}
```

Почитай в интернете разницу

2024-03-16 17:55 UTC, cherninely commented on source/js/video.js
> +  const videos = document.querySelectorAll('.video');
Код опять находится в файле, а не в самовызывающейся функции. Обсуждали в прошлом проекте жеж

2024-03-16 17:55 UTC, cherninely commented on source/js/video.js
> +    setupVideo(videos[i]);
Нужно избегать большой цепочки вложенного вызова функций.
Когда функция вызвает другую и тд. В таком случаи сложно понять как работает в целом код.

Лучше так:

  ```
// Все остальные методы так же.
const findVideo = () => {};

// тут остальные функции

const setupVideo = (video) => {
    // тут достаем все элементы и парсим медиа
    
    const iframeVideoUrl = generateVideoUrl(id);
    
    video.addEventListener('click', () => {
        const iframe = createIframe(iframeVideoUrl);
        video.appendChild(iframe);

        link.remove();
        button.remove();
  });
}

const setupVideos = () => {
    document
        .querySelectorAll('.video')
        .forEach(setupVideo);
};

setupVideos();
```


И все должно быть обернуто в самовызвающуюся функцию. Чтобы не засерать контекст страниуцы.

2024-03-16 17:55 UTC, cherninely commented on source/js/video.js
> +    link.remove();
Этот код в целом не очень понятно зачем. Зачем?

2024-03-16 17:55 UTC, cherninely commented on source/js/video.js
> +  const regexp = /https:\/\/i\.ytimg\.com\/vi\/([a-zA-Z0-9_-]+)\/maxresdefault\.jpg/i;
Все статичные данные должны быть в константах.
Вынеси в константу в корень самовызывающейся функции.

```
const YTIMG_REGEXP = /https:\/\/i\.ytimg\.com\/vi\/([a-zA-Z0-9_-]+)\/maxresdefault\.jpg/i;
```

А здесь подставь уже саму переменную.

2024-03-16 17:55 UTC, cherninely commented on source/js/video.js
> +  const match = url.match(regexp);
В идеале здесь возвращать вообще весь парсинг.
Вдруг в будущем могло бы пригодиться не только конкретный матчинг.

Типа так
```
const [, id] = parseMediaURL(media)
```

2024-03-16 17:55 UTC, cherninely commented on source/sass/blocks/gym.scss
> +  p {
!

2024-03-16 17:55 UTC, cherninely commented on source/sass/blocks/gym.scss
> +    margin: 0;
Оно уже есть выше по дефолту твоему

2024-03-16 17:55 UTC, cherninely commented on source/sass/blocks/video.scss
> +  position: relative;
!

2024-03-16 19:09 UTC, Nostradamusx06 commented on source/index.html
> +    crossorigin="anonymous">
автоматом так ставит

2024-03-16 19:10 UTC, Nostradamusx06 commented on source/index.html
> +            <svg class="video__button-img" width="100" height="100" viewBox="0 0 100 100" fill="none"
Если ты про video, то этот блок отдельно. Если ты про вставку svg в разметку, то так нужно, чтобы я мог состояниями ему цвет менять

2024-03-16 19:31 UTC, Nostradamusx06 commented on source/js/video.js
> +    link.remove();
Когда нажимаю на кнопку - открывается iframe с видео и удаляется моя кастомная кнопка с ссылкой

2024-03-16 19:34 UTC, Nostradamusx06 commented on source/sass/blocks/gym.scss
> +  p {
Мне нужно было верстать эту часть по каскаду типо под CMS. Так требует макет

2024-03-16 19:35 UTC, Nostradamusx06 commented on source/sass/blocks/gym.scss
> +    margin: 0;
На планшетной версии у меня margin: 0 auto.  Я обнуляю auto

2024-03-17 06:48 UTC, cherninely requested changes

2024-03-17 06:48 UTC, cherninely commented on source/js/video.js
> +    const parseMediaURL = (media) => {
Я писал же про функции вложенные в функции.

2024-03-17 06:48 UTC, cherninely commented on source/js/video.js
> +      return match[1];
Не сделал, я писал

2024-03-17 06:48 UTC, cherninely commented on source/js/video.js
> +      const id = parseMediaURL(youtube);
не сделал https://github.com/Nostradamusx06/Fitness/pull/2#discussion_r1527207640

2024-03-17 06:48 UTC, cherninely commented on source/js/video.js
> +      iframe.setAttribute('src', `https://www.youtube.com/embed/${id}${query}`);
Где generate?
Стало хуже.

2024-03-17 06:48 UTC, cherninely commented on source/js/video.js
> +      video.appendChild(iframe);
Не сделал https://github.com/Nostradamusx06/Fitness/pull/2#discussion_r1527207640

2024-03-17 06:48 UTC, cherninely commented on source/js/video.js
> +(function findVideo() {
У тебя фукнцию тут ищет видео? По-моему она делает сильно больше положенного, еще какие-то айфреймы вставлем.
Такие самовызывающиеся функцию можно оставлять без названия, ты их не вызываешь. Зачем тогда имя?

2024-03-17 09:23 UTC, cherninely requested changes
Ты на правки что я написал смотришь или игноришь?
Некоторых правок я не вижу уже 3ю итерацию ревью. Как так????

2024-03-17 09:23 UTC, cherninely commented on source/js/video.js
> +        setupVideo(video);
Передай функцию в аргумент, как я показывал. Вместо стрелочной функции, зачем она?

2024-03-17 09:23 UTC, cherninely commented on source/js/video.js
> +    const youtube = video.querySelector('.video__media');
Лучше так переменные не называть. А если там будет не ютуб? Было лучше

2024-03-17 09:23 UTC, cherninely commented on source/js/video.js
> +  const parseMediaURL = (media) => {
Скобочки у функций с одним аргументом можно не ставить

2024-03-17 09:23 UTC, cherninely commented on source/js/video.js
> +  const createIframe = (src) => {
Тут тоже скобочки не нужны

2024-03-17 09:23 UTC, cherninely commented on source/js/video.js
> +  const setupVideo = (video) => {
Тут тоже скобочки не нужны

2024-03-17 09:23 UTC, cherninely commented on source/js/video.js
> +    const query = '?rel=0&showinfo=0&autoplay=1';
Не добавил функцию, как я просил

2024-03-17 09:29 UTC, Nostradamusx06 commented on source/js/video.js
> +  const parseMediaURL = (media) => {
Линтер требует скобки, не могу убрать

2024-03-17 09:29 UTC, Nostradamusx06 commented on source/js/video.js
> +  const createIframe = (src) => {
Линтер требует скобки, не могу убрать

2024-03-17 09:29 UTC, Nostradamusx06 commented on source/js/video.js
> +  const setupVideo = (video) => {
Линтер требует скобки, не могу убрать

2024-03-17 09:59 UTC, cherninely requested changes

2024-03-17 09:59 UTC, cherninely commented on source/js/video.js
> +    iframe.setAttribute('src', generateURL(id));
Не так.
Я ж тебе скидывал пример.

2024-03-17 13:07 UTC, cherninely requested changes

2024-03-17 13:07 UTC, cherninely commented on source/js/video.js
> +    iframe.setAttribute('src', generateURL(id));
Ты не поправил!

2024-03-17 13:08 UTC, cherninely requested changes

2024-03-17 13:08 UTC, cherninely commented on source/js/video.js
> +    iframe.setAttribute('src', generateURL(id));
Сколько можно!

2024-03-17 13:12 UTC, cherninely commented on source/js/video.js
> +      return match[1];
А еще это не поправил

2024-03-17 13:34 UTC, cherninely requested changes

2024-03-17 13:34 UTC, cherninely commented on source/js/video.js
> +      const videoId = url.match(/[?&]v=([^&#]+)/)[1];
Почему регялрка не в константе опять?

2024-03-17 13:34 UTC, cherninely commented on source/js/video.js
> +      const videoId = url.match(/[?&]v=([^&#]+)/)[1];
Такое чувствл что ты из инетов код тянешь, вставляешь и не думаешь

2024-03-17 13:35 UTC, cherninely requested changes

2024-03-17 13:35 UTC, cherninely commented on source/sass/blocks/gym.scss
> +  p {
Почему это не классом

2024-03-17 13:35 UTC, cherninely commented on source/sass/blocks/gym.scss
> +  p {
Я тебе уже про это писал

2024-03-17 13:36 UTC, Nostradamusx06 commented on source/sass/blocks/gym.scss
> +  p {
Я тебе писал, что мне каскадом надо тут

2024-03-17 14:03 UTC, cherninely requested changes

2024-03-17 14:03 UTC, cherninely commented on source/sass/blocks/gym.scss
> +        margin-left: 11px;
Если вдруг у тебя в секции рядом с `p` будет что-то другое, типа `span`, для них отступа не будет и у тебя контент не будет выровнен по вертикали

2024-03-17 14:03 UTC, cherninely commented on source/sass/blocks/gym.scss
> +        font-size: 16px;
Не сделал

2024-03-17 14:03 UTC, cherninely commented on source/sass/blocks/gym.scss
> +        font-size: 16px;
В остальных p такой же грифт

2024-03-17 14:23 UTC, cherninely approved these changes

2024-03-17 14:24 UTC, merged