Jury block
Nostradamusx06/Fitness pull request #6
Opened 2024-03-22 19:30 UTC by Nostradamusx06

![IMAGE 2024-03-22 22:29:57](https://github.com/Nostradamusx06/Fitness/assets/54951070/a26418e1-75d0-453d-b3a7-60b299c822c3)
![IMAGE 2024-03-22 22:30:02](https://github.com/Nostradamusx06/Fitness/assets/54951070/b802e400-a60f-4fb1-95c5-e0397ff74ad5)
![IMAGE 2024-03-22 22:30:06](https://github.com/Nostradamusx06/Fitness/assets/54951070/2663bf9f-ab8f-4daa-921d-00abe9afe315)
![IMAGE 2024-03-22 22:30:11](https://github.com/Nostradamusx06/Fitness/assets/54951070/d79e171a-a8d0-486c-8b27-035fac5df74b)

2024-03-22 19:48 UTC, cherninely requested changes

2024-03-22 19:48 UTC, cherninely commented on source/js/vendor/vendor.js
> +const coachSwiper = document.querySelector('.coach__slider');
Засираешь контекст страницы, опять двадцать пять.

2024-03-22 19:48 UTC, cherninely commented on source/js/vendor/vendor.js
> +  if (coachSwiper) {
Сделай лучше
```
if(!coachSwiper) {
    return;
}
```

Весь код сдвинется влево.

2024-03-22 19:48 UTC, cherninely commented on source/sass/blocks/button.scss
> +    opacity: 0.5;
Зачем вернул?

2024-03-22 19:48 UTC, cherninely commented on source/sass/blocks/coach-description.scss
> +  position: absolute;
Зачем опять абсолют?

2024-03-22 19:48 UTC, cherninely commented on source/sass/blocks/coach.scss
> +  &:focus .coach-description__name,
Ты в одном блоке(.coach) применяешь стили для другого блока(.coah-description).
Нельзя так, течет абстракция.
Если в будущем вместо этого второго блока будет другой у тебя сломаются все стили

2024-03-22 20:05 UTC, Nostradamusx06 commented on source/sass/blocks/coach-description.scss
> +  position: absolute;
У меня так работает карточка. При наведении и фокусе мне надо, чтобы описание карточки(как на последнем скрине)  появилось. Оно у меня на абсолюте

2024-03-22 20:25 UTC, cherninely commented on source/sass/blocks/coach-description.scss
> +  position: absolute;
Сам по себе блок не должен быть на абсолюте. Тут действует логика как с margin.
Выравниванием блока должен заниматься родителей через элемент на блоке.

2024-03-22 20:26 UTC, cherninely commented on source/sass/blocks/coach-description.scss
> +  position: absolute;
Как здесь переоткрыть коммент епт

2024-03-23 09:40 UTC, cherninely approved these changes

2024-03-23 10:06 UTC, merged