feat: desktop, tablet and mobile versions of the faq block
Nostradamusx06/Fitness pull request #9
Opened 2024-03-26 13:37 UTC by Nostradamusx06

![IMAGE 2024-03-26 16:37:18](https://github.com/Nostradamusx06/Fitness/assets/54951070/ec8506b0-957b-4cd6-a527-4960cc120cb8)
![IMAGE 2024-03-26 16:37:21](https://github.com/Nostradamusx06/Fitness/assets/54951070/7d104731-3200-4a58-a0ac-cd87935eb863)
![IMAGE 2024-03-26 16:37:24](https://github.com/Nostradamusx06/Fitness/assets/54951070/8f27db29-0827-41af-bf99-f73148e1dc9b)
![IMAGE 2024-03-26 16:37:27](https://github.com/Nostradamusx06/Fitness/assets/54951070/0a8e35cc-7de9-4431-97cb-d37b36a4e9ae)

2024-03-26 14:12 UTC, cherninely requested changes
Плохо.
Тебе нужно всего лишь для кнопок:
* обработать клик кнопки и получить ее index
* сбросить active для у кнопок и аккордеонов
* сделать текущую кнопку активной и дефолтнй аккордеон
* достать из кнопки данные и вставить в аккордеон

Почему так сложно и так много кода то?

2024-03-26 14:12 UTC, cherninely commented on source/index.html
> +                data-questions="Как стать членом фитнес-&#8288;центра?__Где можно посмотреть расписание?__Есть кулеры в центре? Предоставляются полотенца?__Сколько тренеров работает в клубе и какова
Храни в формате JSON.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +  const firstAccordionItem = accordionItems[0];
Откуда ты знаешь что default первый?
Ты в html уже зашил первый и по html ты это можешь понять.
Раз ты зашил по дефолту текст первого, так положи в html и active для первого.

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +  openedItems.add(firstAccordionItem);
Зачем ты кладешь в Set ноду html?
Оперируй индексами.

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +  const firstAccordionItem = accordionItems[0];
А лучше вообще в html ничего не хранить, даже текста дефолтного.
Лучше завести переменную типа `DEFAULT_INDEX`, в нее положить индекс который должен быть по дефолту.
Потом взять из нее значение и сделать этот индекс активными.
У тебя может быть функция `activateDefaultЧто-то`

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +    button.addEventListener('click', () => {
Выучи что такое делегирование событий. Ты можешь один раз сделать `addEventListener` на все кнпоки.

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +      spans.forEach((span) => {
Выглядит как функция `unactivateЧто-то`

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +        itemButton.textContent = questions[index % questions.length];
Зачем это? Чего так сложно?

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +          item.classList.add('faq__accordion-item--active');
Дублирование кода

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +        item.classList.remove('faq__accordion-item--active');
Дублироване кода

2024-03-26 14:12 UTC, cherninely commented on source/js/accordion.js
> +        item.classList.add('faq__accordion-item--active');
Дублирование кода

2024-03-26 14:12 UTC, cherninely commented on source/js/tabs.js
> +  const allButtons = document.querySelectorAll('.faq__item-button');
Как это связано с подписками выше по файлу?

2024-03-26 18:00 UTC, cherninely requested changes

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +  const faqData = {
Ты мог в data-* положить прям JSON.
Прочитай документацию. JSON.stringify превращает json в строку. А JSON.parse превращает строку в json.
Но так тоже норм.

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +        title: 'Центр',
Правильней хранить для каждого элемента `{question: "sdasdasd", answer: "asdasdasdsasd"}`
Но не критично.
Главное чтобы ты идею понял.

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +  function activateTab(index) {
const!!!!!!!!
сколько можно

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +    buttons.forEach((button) => button.classList.remove('faq__item-button--active'));
У тебя функция использует переменную из внешнего скоупа.
Лучше передавать в аргумент, потому что с такой функцию потом сложно работать.
Ты можешь случайно прокинуть в функцию аргумент, назвать его тоже buttons и у тебя все перестанет работать. Понял?

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +      const item = accordionItems[itemIndex];
Вот если сделал бы объект как я выше написал не пришлось бы такое писать.
У тебя  аргументах функции сразу был бы и вопрос и ответ.

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +      if (itemIndex === 0) {
Вот этот код я чот вообще не понял нахрена он

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +    span.classList.toggle('faq__answer--closed');
Почему не может быть по дефолту закрыт и только при `active` открыт? Зачем 2 класса?

2024-03-26 18:00 UTC, cherninely commented on source/js/accordion.js
> +    button.addEventListener('click', () => activateTab(index));
А где делегирование которое я просил?

2024-03-27 06:01 UTC, cherninely requested changes

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +  const DEFAULT_ITEM = accordionItems[DEFAULT_INDEX];
Это не константа. Константа — это что-то статичное. А items априориоре не статичные, потому что когда это сайт они могут изи меняться

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +          { question: 'Как стать членом фитнес\u2011центра?', answer: 'При первом посещении и покупке абонемента, необходимо заполнить анкету и\u00A0подписать договор. При покупке абонемента онлайн,
Для удобства чтения json лучше разворачивать вот так
```json
{
    question: '1231231',
    answer: '123123123'
}
```

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +  firstSpan.classList.add('faq__answer--active');
Почему не так?

```
DEFAULT_ITEM
    .querySelector('span')
    .classList.add('faq__answer--active');
```

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +  openedItems.add(DEFAULT_ITEM);
Я же тебе писал: https://github.com/Nostradamusx06/Fitness/pull/9#discussion_r1539298726

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +  activateTab(DEFAULT_INDEX, buttons, accordionItems);
Не понимаю. Ты выше почему-то выставляешь active https://github.com/Nostradamusx06/Fitness/pull/9/files#diff-2b0c2d75659fb9b212cdc738facfe0cb9a56a2c43a0451baa48deee920cd9200R109

И тут вызываешь active? Почему???

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +  accordionItems.forEach((item) => {
Выше добавил делегирование. А тут почему нет? accordion особенный?

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +    buttonsArray.forEach((button) => button.classList.remove('faq__item-button--active'));
Я не понимаю. У тебя в html button уже стоит active: https://github.com/Nostradamusx06/Fitness/pull/9/files#diff-2d7f1f1674143252d45bafff792f025edb37f384958f37ae50cfdf3ddeb03c7eR596
А тут ты его сразу удаляешь. Что за прикол?

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +      const span = item.querySelector('span');
Я же тебе писал: https://github.com/Nostradamusx06/Fitness/pull/9#discussion_r1539310783

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +    buttonsArray.forEach((button) => button.classList.remove('faq__item-button--active'));
Нафига этот код вообще здесь внутри activateTab? Этот код его разве активирует?
Почему нельзя так?

```
resetButtonsToDefault(buttonsArray);
resetAccordionToDefault(accordionItemsArray);
activateTab(tab);
```

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +    const tab = faqData.tabs[index];
tabData.
А то читаешь и схожу кажется что там html

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +    accordionItemsArray.forEach((item) => {
Какое отношение к табам имеет аккордеон? Почему он в функции activateTab?

2024-03-27 06:01 UTC, cherninely commented on source/js/accordion.js
> +    span.classList.toggle('faq__answer--closed');
Я же писал

2024-03-27 09:34 UTC, Nostradamusx06 commented on source/js/accordion.js
> +    buttonsArray.forEach((button) => button.classList.remove('faq__item-button--active'));
Когда нажимаю на другую кнопку, то active должен удалиться у прошлой кнопки и потом добавится на другую. Эта строчка отвечает за удаление active с прошлой кнопки

2024-03-27 17:36 UTC, cherninely requested changes

2024-03-27 17:36 UTC, cherninely commented on source/js/accordion.js
> +    resetButtonsToDefault(buttonsArray);
Не поправлено

2024-03-27 17:36 UTC, cherninely commented on source/js/accordion.js
> +    resetAccordionToDefault(accordionItemsArray);
Не поправлено

2024-03-27 17:36 UTC, cherninely commented on source/js/accordion.js
> +  const initAccordion = (accordionItemsArray, tabData) => {
Почему у тебя включение таба называется `activateTab`, а включение аккордеона называется `initAccordion`?
Потому что данные вставляются?
Ну вынеси методы:
```
updateAccordionData(...);
activateAccordion(....)
```

2024-03-27 17:36 UTC, cherninely commented on source/js/accordion.js
> +      if (item.classList.contains('faq__accordion-item--active')) {
Почему у тебя тут добавляется `active` и так же добавляется в toggle? Нафига в 2х местах?

2024-03-27 17:36 UTC, cherninely commented on source/js/accordion.js
> +      accordionItem.classList.toggle('faq__accordion-item--active', isOpened);
Почему здесь тоже самое что в toggle?

2024-03-27 17:36 UTC, cherninely commented on source/js/accordion.js
> +    activateTab(index, buttons);
Ты ведь уже знаешь конкретнвй button. Не надо передавать все кнопки.
Оперируй индексами.
Обсуждали уже

2024-03-28 17:39 UTC, cherninely approved these changes
Уже хорошо.
Я тебе замечания написал. Править не критично. Но чтобы знал.

2024-03-28 17:39 UTC, cherninely commented on source/js/accordion.js
> +  const toggleAccordionItemState = (accordionItem, span, isOpened, tabIndex) => {
Тебе надо `openedItems[tabIndex]` снаружи вместо индекса прокидывать.
Аккордеон ничего не должен знать про своего родиля таба.

2024-03-28 17:39 UTC, cherninely commented on source/js/accordion.js
> +  openedItems[DEFAULT_INDEX] = new Set([DEFAULT_INDEX]);
Ты же `openedItems` внутри `toggleAccordionItemState` заполняешь этим индексом. Зачем тут перетираешь?
Или я чот не туда смотрю?

2024-03-28 17:39 UTC, cherninely commented on source/js/accordion.js
> +    activateTab(index);
Сначала `resetButtons` , потом `activateTab`. Ты уж определись с чем ты работает — с табами или кнопками.

2024-03-28 17:39 UTC, cherninely commented on source/js/accordion.js
> +      toggleAccordionItemState(accordionItem, span, isOpened, tabIndex);
Почему ты `toggle` делаешь внутри `update`?
Когда я читаю название функции она как-будто только обновляет, а не тоглит еще.

2024-03-28 19:35 UTC, merged